//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GraphicalOutput.java
//  @ Date : 10/30/2006
//  @ Author : 
//
//



package blink.cli;


public class GraphicalOutput {
}
