//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Assignment.java
//  @ Date : 10/30/2006
//  @ Author :
//
//
package blink.cli;


public class NodeAssignment extends Node {

    private String _identifier;

    private Node _valueNode;

    public NodeAssignment(String identifier, Node valueNode) {
        _identifier = identifier;
        _valueNode = valueNode;
    }

    public String getIdentifier() {
        return _identifier;
    }

    public Node valueNode() {
        return _valueNode;
    }

    public Object evaluate() throws EvaluationException {
        return CommandLineInterface.getInstance().evaluateNodeAssignment(this);
    }
}
