//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ScriptNode.java
//  @ Date : 10/30/2006
//  @ Author :
//
//
package blink.cli;


public abstract class Node {

    public void ScriptNode(Object identifier) {
    }

    public abstract Object evaluate() throws EvaluationException;

}
