//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Variable.java
//  @ Date : 10/30/2006
//  @ Author :
//
//

package blink.cli;

public class NodeVariable extends Node {

    private String _identifier;

    private NodeIndex _index;

    public NodeVariable(String identifier, NodeIndex index) {
        _identifier = identifier;
        _index = index;
    }

    public NodeIndex getIndex() {
        return _index;
    }

    public String getIdentifier() {
        return _identifier;
    }

    public Object evaluate() throws EvaluationException {
        return CommandLineInterface.getInstance().evaluateNodeVariable(this);
    }

}
