//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TextOutput.java
//  @ Date : 10/30/2006
//  @ Author :
//
//



package blink.cli;


public interface TextOutput {
    public void write(String text);
}
